[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:xtigervnc]
priority=0
command=/usr/bin/Xtigervnc -desktop "Kodi" -rfbport %(ENV_VNC_PORT)s -SecurityTypes None -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText -geometry %(ENV_KODI_RESOLUTION)s -depth 24 :99
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
priority=0
command=/usr/bin/websockify --web=/usr/share/novnc/ %(ENV_NOVNC_PORT)s localhost:%(ENV_VNC_PORT)s
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:kodi]
priority=1
environment=DISPLAY=:99,KODI_HOME=/usr/share/kodi
command=/usr/bin/kodi --standalone --windowing=x11
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
